// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wmomluulwikqdkmwxccn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indtb21sdXVsd2lrcWRrbXd4Y2NuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxMDA2MjQsImV4cCI6MjA1ODY3NjYyNH0.EbKs1vLMvkJJtHQNQIj45fh7txmY1VUxGakd7HE8x1s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);